### ISSUE TITLE
Compile error in SCCAMSlot.cpp

### ISSUE THREAD

**Issue by Fuchks** [manio/vdr-plugin-dvbapi#125] opened 2018-02-05 01:34 UTC
```
*** Plugin dvbapi:
g++ -g -O3 -Wall -Werror=overloaded-virtual -Wno-parentheses -fPIC -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -c -DPLUGIN_NAME_I18N='"dvbapi"' -DGITVERSION='"-GIT-7d51cc4"' -DLIBSSL -I/usr/local/src/vdr-2.2.0/include  -o SCCAMSlot.o SCCAMSlot.cpp
SCCAMSlot.cpp: In constructor ‘SCCAMSlot::SCCAMSlot(SCCIAdapter*, int, int, cCamSlot*)’:
SCCAMSlot.cpp:41:36: error: no matching function for call to ‘cCamSlot::cCamSlot(SCCIAdapter*&, bool, cCamSlot*&)’
  , decsaFillControl(200000, 100, 40)
                                    ^
SCCAMSlot.cpp:41:36: note: candidates are:
In file included from SCCAMSlot.cpp:27:0:
/usr/local/src/vdr-2.2.0/include/vdr/ci.h:158:3: note: cCamSlot::cCamSlot(cCiAdapter*, bool)
   cCamSlot(cCiAdapter *CiAdapter, bool WantsTsData = false);
   ^
/usr/local/src/vdr-2.2.0/include/vdr/ci.h:158:3: note:   candidate expects 2 arguments, 3 provided
/usr/local/src/vdr-2.2.0/include/vdr/ci.h:130:7: note: cCamSlot::cCamSlot(const cCamSlot&)
 class cCamSlot : public cListObject {
       ^
/usr/local/src/vdr-2.2.0/include/vdr/ci.h:130:7: note:   candidate expects 1 argument, 3 provided
make[1]: *** [SCCAMSlot.o] Fehler 1

*** failed plugins: dvbapi

make: *** [plugins] Fehler 1

```

**Comment by manio** [comment] 2018-02-05 10:24
Duplicate of #124
The master branch is always the development code which should work for recent VDR developer versions. I am making stable releases from time to time (https://github.com/manio/vdr-plugin-dvbapi/releases) and if you are using older VDR, just use the latest stable release which is compatible with the VDR you are using. Closing.

**Closed by manio** 2018-02-05 10:24 UTC

**Comment by Fuchks** [comment] 2018-02-05 17:04
Ahh, should have read the closed issues before ;-)
Would be nice, if this would be mentioned in the readme or install file -> difference dev and release
