### ISSUE TITLE
service API seems to fail sometimes

### ISSUE THREAD

**Issue by mat130780** [manio/vdr-plugin-dvbapi#100] opened 2015-09-16 16:30 UTC
Hi,

the VDR skindesigner plugin uses the plugin's service API in order to display some crypt info (reader, ECM time, CAID etc.) However this does not always work reliably, sometimes the data are missing. 
I tested this with dvbapi log level = 3. Here is a log when the data are shown correctly:
Sep 13 13:37:12 htpc vdr: [12544] DVBAPI: UpdateEcmInfo: PMTO update, adapter=0, SID=EF75
Sep 13 13:37:12 htpc vdr: [12435] connect from 127.0.0.1, port 49895 - accepted
Sep 13 13:37:19 htpc vdr: [14628] DVBAPI: Analyze: all data in one TS packet, immediate send
Sep 13 13:37:19 htpc vdr: [14628] DVBAPI: Write, sock=17
Sep 13 13:37:19 htpc vdr: [14628] DVBAPI: socket_fd=17 len=152 wrote=152
Sep 13 13:37:19 htpc vdr: [12544] DVBAPI: Action: Got DMX_SET_FILTER request, adapter_index=0, pid=1CEC, demux_idx=0, filter_num=0
Sep 13 13:37:19 htpc vdr: [12544] DVBAPI: SetFilter: adapter=0 set FILTER pid=1CEC start=1, demux=0, filter=0
Sep 13 13:37:19 htpc vdr: [12544] DVBAPI:    --> FILTER: 81 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Sep 13 13:37:19 htpc vdr: [12544] DVBAPI:    -->   MASK: FF 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Sep 13 13:37:19 htpc vdr: [12544] DVBAPI: SetFilter: filter update, demux=0, filter_num=0
Sep 13 13:37:19 htpc vdr: [12544] DVBAPI: Action: Got CA_SET_DESCR request, adapter_index=0
Sep 13 13:37:19 htpc vdr: [12544] DVBAPI: SetDescr
Sep 13 13:37:19 htpc vdr: [12544] DVBAPI: 0.0:  odd key set
Sep 13 13:37:19 htpc vdr: [12544] DVBAPI: Action: Got ECM_INFO: adapter_index=0, SID = EF75, CAID = 1830 (nagra), PID = 1CEC, ProvID = 000000, ECM time = 95 ms, reader = oscam_cccam, from = blablabla.net, protocol = cccam_ext, hops = 1

Here is a log when no data are shown:
Sep 13 17:50:31 htpc vdr: [3186] DVBAPI: Action: Got DMX_SET_FILTER request, adapter_index=1, pid=1CCE, demux_idx=0, filter_num=0
Sep 13 17:50:31 htpc vdr: [3186] DVBAPI: SetFilter: adapter=1 set FILTER pid=1CCE start=1, demux=0, filter=0
Sep 13 17:50:31 htpc vdr: [3186] DVBAPI:    --> FILTER: 81 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Sep 13 17:50:31 htpc vdr: [3186] DVBAPI:    -->   MASK: FF 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Sep 13 17:50:31 htpc vdr: [3186] DVBAPI: SetFilter: filter update, demux=0, filter_num=0
Sep 13 17:50:32 htpc vdr: [3063] DVBAPI: FillEcmInfo: PMTO match - fill, adapter=0, SID=EF75
Sep 13 17:50:32 htpc vdr: [3186] DVBAPI: Action: Got CA_SET_DESCR request, adapter_index=1
Sep 13 17:50:32 htpc vdr: [3186] DVBAPI: SetDescr
Sep 13 17:50:32 htpc vdr: [3186] DVBAPI: 0.0:  odd key set
Sep 13 17:50:32 htpc vdr: [4195] DVBAPI: Analyze: all data in one TS packet, immediate send
Sep 13 17:50:32 htpc vdr: [4195] DVBAPI: Write, sock=99
Sep 13 17:50:32 htpc vdr: [4195] DVBAPI: socket_fd=99 len=152 wrote=152

You can see the line with Action: "Got ECM_INFO: ..." is missing here, thus no information is available although I had switch to an encrypted channel. 
Could it be that that the API gets "confused" in case oscam is started *after* VDR has been started, or if oscam crashes and is restarted while VDR is running?

Thanks.

**Comment by manio** [comment] 2015-09-16 19:22
Hello
Generally if vdr is able to decrypt, then it is connected and the ECM_INFO is sending over the same TCP socket, so it should be not "confused" in cases you mentioned.

Please try this patch in the oscam: http://pastebin.com/ZUfYXnY9
This will drop you a line in the log when the ECM_INFO is sent *from* the oscam to the plugin.
If you will be able to reproduce the problem, please note if the line is still showing in the oscam log.

**Comment by mat130780** [comment] 2015-09-19 18:10
Hi!
I have patched and compiled the current scam version and followed your request. Please have a look at these logs:
http://pastebin.com/download.php?i=vm5KUCmk   <- This is an extract from oscam.log. Please compare the log messages before and after 13:30h. After 13:30h there seems to be no proper connection from oscam to dvbapi, however decryption of the channels was working OK, only the info was missing. 
http://pastebin.com/download.php?i=N280Xd23   <- This log was created with command "tail -f /var/log/syslog | grep DVBAPI" and covers the same time period. Again, the time after 13:30h is the interesting period where the data were not forwarded properly.

**Comment by MegaV0lt** [comment] 2015-09-20 06:33
Links not working... Try that ones:
http://pastebin.com/raw.php?i=vm5KUCmk
http://pastebin.com/raw.php?i=N280Xd23

**Comment by manio** [comment] 2015-09-20 14:58
Yes, i discovered that links myself. I can see that there is something wrong in the oscam after it's restart. Maybe some flag is cleared and it leads to problems after crash/restart. I'll try to look at it when i have some time.

**Comment by mat130780** [comment] 2015-09-20 15:36
Thanks a lot in advance!

**Comment by manio** [comment] 2015-09-20 16:27
I think that the problem is in the current code for the discovering if oscam is new or old (if oscam is not up when VDR is starting, it will fallback to "legacy" oscam mode). It will be dropped some day, so instead of fixing it (creating another workaround) i prepared a quick patch for you to test:
http://pastebin.com/AadkNqWw

You may use it currently if it works ok. Please try if the problem is gone.

**Comment by mat130780** [comment] 2015-09-20 18:15
Thanks, I have installed dvbapi with the patch included and will test for the next if I the issue will occur again.

**Comment by mat130780** [comment] 2015-09-24 16:44
I have tested for several days with different scenarios (start of oscam before and after VDR, crashed VDR etc.), and the issue did not occur again. The patch seems to work :-)

**Comment by MegaV0lt** [comment] 2015-12-09 12:40
Can you reupload the patch? The page was removed

**Comment by manio** [comment] 2015-12-09 12:44
@mat130780, you still have it?
Please paste it via pastebin, I created it temporarily and even don't remember exact content.

**Comment by mat130780** [comment] 2015-12-09 20:00
Couldn't find it quickly, I will have a look at the backups next weekend. Please remind ne on Sunday if I have not replied till then.

**Comment by mat130780** [comment] 2015-12-12 12:00
Hi, 

I found it on my 2nd VDR machine: http://pastebin.com/u9vp89NL

**Comment by manio** [comment] 2016-01-14 05:19
I think the problem should be now solved with my recent fix ([rev 11209](http://www.streamboard.tv/oscam/changeset/11209)). Closing.

**Closed by manio** 2016-01-14 05:19 UTC
