### ISSUE TITLE
vdr-plugin-dvbapi does not work with oscam >= r11195

### ISSUE THREAD

**Issue by 3PO** [manio/vdr-plugin-dvbapi#102] opened 2015-12-05 17:44 UTC
the support für the vdr-dvbapi Plugin is broken since oscam r11195.

further Information --> http://www.streamboard.tv/wbb2/thread.php?postid=556366#post556366

**Comment by 3PO** [comment] 2015-12-20 17:24
Any News?

**Comment by manio** [comment] 2015-12-20 19:28
If it was working before, and now after some OSCam changes it is broken then I think the changes which broke it are in the OSCam. The plugin was untouched for a longer time period. If the problem is in the dvbapi plugin, please provide a log and point me where you suspect if differ from a working version. The plugin just sends a PMT data to the OSCam - that's all - what have I to fix which was working before?

Maybe try this: http://pastebin.com/E7qcERWr ?

If theparasol is telling something about closing socket - It is as I was explaining before: the plugin is using single socket for all decoding, and it is not closing the socket, but sending the DVBAPI_DMX_STOP command to stop descrambling. The connection is still open to allow faster zap times when starting a channel again.

**Comment by manio** [comment] 2015-12-21 08:49
@3PO - is it working with the mentioned patch?

**Comment by 3PO** [comment] 2015-12-21 16:42
- The patch doesnt work. :(
- yes your right, the last working Revision is 11194.

with patched dvbapi Plugin and oscam r11200, i get the folowing issue:

--> https://bpaste.net/show/5323f0595e73

**Comment by manio** [comment] 2015-12-21 21:41
I am now using OSCam r11200 and my latest master plugin. I am trying to reproduce the problem using a recordings. When I enabled the recording, it successfully start decoding, when i disabled it - it stops, and it is correctly sending the "stop descrambling" command; the socket is left open, and when i re-enabled timer again, it is recording back again. So all is working fine for me.
Can you reproduce the problem using recording and activating/deactivating timer? Maybe i have to try harder with normal zapping, what do you think?

**Comment by 3PO** [comment] 2015-12-22 16:54
Recording, i've never tested.

When i update oscam to >= r11195 and  switch to a encypted channel, i get a black Screen and in the log i find the issue i posted above.

**Comment by manio** [comment] 2015-12-22 18:54
@3PO Sorry - no idea how to reproduce your problem. I also asked on IRC if the guys there also have similar problems - no one has. Maybe it is related with your channels/config/oscam configuration etc...

**Comment by manio** [comment] 2015-12-23 02:00
@3PO From IRC discussion: I don't know if it is related with your problem, but you may also try this patch: http://www.vdr-portal.de/board16-video-disk-recorder/board99-distributionen/board96-yavdr/p1258103-vdr-startet-auf-genau-einem-sender-n-tv-hd-einfach-neu/#post1258103

**Comment by FrodoVDR** [comment] 2015-12-23 08:03
@manio I have the same issue and the patch from the vdr-portal was included on my VDR.

Dec 23 08:52:44 vdr4 vdr: [2406] switching to channel 35
Dec 23 08:52:44 vdr4 vdr: [2406] CAM 1: assigned to device 1
Dec 23 08:52:44 vdr4 vdr: [2406] DVBAPI: 0.0 CA_PMT decoding len=28 lm=4 prg=131 len=13
Dec 23 08:52:44 vdr4 vdr: [2406] DVBAPI: ci_cmd(G)=01
Dec 23 08:52:44 vdr4 vdr: [2406] DVBAPI: pid=2,04ff len=0 (0x0)
Dec 23 08:52:44 vdr4 vdr: [2406] DVBAPI: pid=6,0503 len=0 (0x0)
Dec 23 08:52:44 vdr4 vdr: [2406] DVBAPI: pid=6,0504 len=0 (0x0)
Dec 23 08:52:44 vdr4 vdr: [2406] DVBAPI: 0.0 got CA pmt ciCmd=1 caLm=4
Dec 23 08:52:44 vdr4 vdr: [2406] DVBAPI: 0.0 answer to query suppressed
Dec 23 08:52:44 vdr4 vdr: [2406] DVBAPI: 0.0 set CAM decrypt (SID 131 (0x0083), caLm 4, HasCaDescriptors 1)
Dec 23 08:52:44 vdr4 vdr: [2406] DVBAPI: send: channelSid=0x83 (131)
Dec 23 08:52:44 vdr4 vdr: [2406] DVBAPI: Write, sock=58
Dec 23 08:52:44 vdr4 vdr: [2406] DVBAPI: socket_fd=58 len=50 wrote=50
Dec 23 08:52:44 vdr4 vdr: [22093] device 1 receiver thread started (pid=2406, tid=22093, prio=high)
Dec 23 08:52:44 vdr4 vdr: [2806] DVBAPI-Error: Action: read failed unknown command: 002b6f3c
Dec 23 08:52:44 vdr4 vdr: [2806] DVBAPI-Error: Action: read failed unknown command: 00000000
Dec 23 08:52:44 vdr4 vdr: message repeated 3 times: [ [2806] DVBAPI-Error: Action: read failed unknown command: 00000000]
Dec 23 08:52:44 vdr4 vdr: [2806] DVBAPI-Error: Action: read failed unknown command: ff000000
Dec 23 08:52:44 vdr4 vdr: [2806] DVBAPI-Error: Action: read failed unknown command: 00000000
Dec 23 08:52:44 vdr4 vdr: message repeated 5 times: [ [2806] DVBAPI-Error: Action: read failed unknown command: 00000000]
Dec 23 08:52:44 vdr4 vdr: [2806] DVBAPI-Error: Action: read failed unknown command: 00000004
Dec 23 08:52:44 vdr4 vdr: [2806] DVBAPI-Error: Action: read failed unknown command: 0000002b
Dec 23 08:52:44 vdr4 vdr: [2806] DVBAPI-Error: Action: read failed unknown command: 3c400001
Dec 23 08:52:44 vdr4 vdr: [2806] DVBAPI-Error: Action: read failed unknown command: 1a800000
Dec 23 08:52:44 vdr4 vdr: [2806] DVBAPI-Error: Action: read failed unknown command: 00000000
Dec 23 08:52:44 vdr4 vdr: [2806] DVBAPI-Error: Action: read failed unknown command: 00000000
Dec 23 08:52:44 vdr4 vdr: [2806] DVBAPI-Error: Action: read failed unknown command: 0000f000
Dec 23 08:52:44 vdr4 vdr: [2806] DVBAPI-Error: Action: read failed unknown command: 00000000
Dec 23 08:52:45 vdr4 vdr: message repeated 5 times: [ [2806] DVBAPI-Error: Action: read failed unknown command: 00000000]
Dec 23 08:52:45 vdr4 vdr: [2806] DVBAPI-Error: Action: read failed unknown command: 00b80b00

**Comment by MegaV0lt** [comment] 2015-12-23 08:42
@3PO when you have the "unknown command" try to restart oscam on the server and see if it working then. In the past that was working here. I still only have 11194 running here.

@manio 
when "unknown" command can be fixed by oscam restart i think the dvbapi has to do a better connectioncheck with oscam in network mode.

**Comment by manio** [comment] 2015-12-23 12:43
@FrodoVDR @MegaV0lt 
So my patch http://pastebin.com/E7qcERWr is not working for the "unknown command" problems?

**Comment by MegaV0lt** [comment] 2015-12-23 12:48
in the 11194 it is not needed. I can not test until early january. At least in 3PO's log ist isnt' working.

**Comment by FrodoVDR** [comment] 2015-12-23 19:58
@manio
The patch works not correct for me. The same "unknown command" I see in logfile.

But in the test, I noticed that the new versions Oscam work.
Apparently only the first link between dvbapi plugin and newer versions Oscam r11194 is disturbed.
If the VDR is connected over DVBAPI already to Oscam r11194 also works a newer version, unfortunately, only when switching during operation of Oscam version r11194 to Oscam version r11200.

**Comment by manio** [comment] 2015-12-25 11:36
Closing as the problem is not occurs in recent OSCams, it's probably two problems in the same issue, and discussion has moved to the streamboard thread.

**Closed by manio** 2015-12-25 11:36 UTC
